<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class SekolahCianjurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        $dataSekolah = [
            // --- KECAMATAN SUKALUYU ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMAN 1 Sukaluyu',
                'nss' => '301020714046',
                'npsn' => '20252046',
                'kode_sekolah' => 'SMAN1SKL',
                'bentuk_pendidikan_id' => 6,
                'bentuk_pendidikan_id_str' => 'SMA',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Bojongsari, Sukamulya',
                'rt' => '01', 'rw' => '02',
                'kode_wilayah' => '020714',
                'kode_pos' => '43284',
                'nomor_telepon' => '0263-228001',
                'email' => 'info@sman1sukaluyu.sch.id',
                'website' => 'sman1sukaluyu.sch.id',
                'lintang' => '-6.818500', 'bujur' => '107.235600',
                'kecamatan' => 'Kec. Sukaluyu',
                'kabupaten_kota' => 'Kab. Cianjur',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMK Plus Al-Ittihad',
                'nss' => '402020714088',
                'npsn' => '69752134',
                'kode_sekolah' => 'SMKALIT',
                'bentuk_pendidikan_id' => 15,
                'bentuk_pendidikan_id_str' => 'SMK',
                'status_sekolah' => 2,
                'status_sekolah_str' => 'Swasta',
                'alamat_jalan' => 'Jl. Raya Bandung KM 9, Bojong',
                'rt' => '03', 'rw' => '05',
                'kode_wilayah' => '020714',
                'kode_pos' => '43284',
                'nomor_telepon' => '0263-229002',
                'email' => 'admin@smkalittihad.sch.id',
                'website' => 'smkalittihad.sch.id',
                'lintang' => '-6.822100', 'bujur' => '107.241200',
                'kecamatan' => 'Kec. Sukaluyu',
                'kabupaten_kota' => 'Kab. Cianjur',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            // --- KECAMATAN BOJONGPICUNG ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMAN 1 Bojongpicung',
                'nss' => '301020709033',
                'npsn' => '20206822',
                'kode_sekolah' => 'SMAN1BJP',
                'bentuk_pendidikan_id' => 6,
                'bentuk_pendidikan_id_str' => 'SMA',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Terusan Jati, Bojongpicung',
                'rt' => '05', 'rw' => '01',
                'kode_wilayah' => '020709',
                'kode_pos' => '43283',
                'nomor_telepon' => '0263-321003',
                'email' => 'sman1bjp@gmail.com',
                'website' => 'sman1bojongpicung.sch.id',
                'lintang' => '-6.835400', 'bujur' => '107.278900',
                'kecamatan' => 'Kec. Bojongpicung',
                'kabupaten_kota' => 'Kab. Cianjur',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMK Nurul Islam Affandiyah',
                'nss' => '402020709045',
                'npsn' => '20252399',
                'kode_sekolah' => 'SMKNURIS',
                'bentuk_pendidikan_id' => 15,
                'bentuk_pendidikan_id_str' => 'SMK',
                'status_sekolah' => 2,
                'status_sekolah_str' => 'Swasta',
                'alamat_jalan' => 'Jl. Raya Bojongpicung No. 12',
                'rt' => '01', 'rw' => '04',
                'kode_wilayah' => '020709',
                'kode_pos' => '43283',
                'nomor_telepon' => '0263-322004',
                'email' => 'info@smknurulislam.sch.id',
                'website' => null,
                'lintang' => '-6.840100', 'bujur' => '107.281000',
                'kecamatan' => 'Kec. Bojongpicung',
                'kabupaten_kota' => 'Kab. Cianjur',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            // --- KECAMATAN CIRANJANG ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMKN 1 Ciranjang',
                'nss' => '401020708001',
                'npsn' => '20207019',
                'kode_sekolah' => 'SMKN1CRJ',
                'bentuk_pendidikan_id' => 15,
                'bentuk_pendidikan_id_str' => 'SMK',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Jati Pasiripis, Ciranjang',
                'rt' => '02', 'rw' => '09',
                'kode_wilayah' => '020708',
                'kode_pos' => '43282',
                'nomor_telepon' => '0263-326005',
                'email' => 'smkn1ciranjang@yahoo.com',
                'website' => 'smkn1ciranjang.sch.id',
                'lintang' => '-6.809000', 'bujur' => '107.265000',
                'kecamatan' => 'Kec. Ciranjang',
                'kabupaten_kota' => 'Kab. Cianjur',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            // --- KECAMATAN MANDE ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMAN 1 Mande',
                'nss' => '301020713042',
                'npsn' => '20252044',
                'kode_sekolah' => 'SMAN1MND',
                'bentuk_pendidikan_id' => 6,
                'bentuk_pendidikan_id_str' => 'SMA',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. R.H. Aria Natamanggala, Mande',
                'rt' => '04', 'rw' => '02',
                'kode_wilayah' => '020713',
                'kode_pos' => '43292',
                'nomor_telepon' => '0263-226006',
                'email' => 'sman1mande@sch.id',
                'website' => null,
                'lintang' => '-6.782000', 'bujur' => '107.195000',
                'kecamatan' => 'Kec. Mande',
                'kabupaten_kota' => 'Kab. Cianjur',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMAN 3 Bandung',
                'nss' => '301026001003',
                'npsn' => '20219256',
                'kode_sekolah' => 'SMAN3BDG',
                'bentuk_pendidikan_id' => 6,
                'bentuk_pendidikan_id_str' => 'SMA',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Belitung No. 8',
                'rt' => '03', 'rw' => '01',
                'kode_wilayah' => '026001',
                'kode_pos' => '40113',
                'nomor_telepon' => '022-4235154',
                'email' => 'info@sman3bandung.sch.id',
                'website' => 'sman3bandung.sch.id',
                'lintang' => '-6.912300', 'bujur' => '107.616100',
                'kecamatan' => 'Kec. Sumur Bandung',
                'kabupaten_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMAN 5 Bandung',
                'nss' => '301026001005',
                'npsn' => '20219254',
                'kode_sekolah' => 'SMAN5BDG',
                'bentuk_pendidikan_id' => 6,
                'bentuk_pendidikan_id_str' => 'SMA',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Belitung No. 8',
                'rt' => '03', 'rw' => '01',
                'kode_wilayah' => '026001',
                'kode_pos' => '40113',
                'nomor_telepon' => '022-4203393',
                'email' => 'admin@sman5bandung.sch.id',
                'website' => 'sman5bandung.sch.id',
                'lintang' => '-6.912400', 'bujur' => '107.616200',
                'kecamatan' => 'Kec. Sumur Bandung',
                'kabupaten_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            // --- KECAMATAN COBLONG ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMAN 1 Bandung',
                'nss' => '301026002001',
                'npsn' => '20219258',
                'kode_sekolah' => 'SMAN1BDG',
                'bentuk_pendidikan_id' => 6,
                'bentuk_pendidikan_id_str' => 'SMA',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Ir. H. Juanda No. 93',
                'rt' => '02', 'rw' => '03',
                'kode_wilayah' => '026002',
                'kode_pos' => '40132',
                'nomor_telepon' => '022-2506292',
                'email' => 'sman1bdg@yahoo.com',
                'website' => 'sman1bdg.sch.id',
                'lintang' => '-6.892100', 'bujur' => '107.613500',
                'kecamatan' => 'Kec. Coblong',
                'kabupaten_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            // --- KECAMATAN LENGKONG ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMKN 3 Bandung',
                'nss' => '401026003003',
                'npsn' => '20219152',
                'kode_sekolah' => 'SMKN3BDG',
                'bentuk_pendidikan_id' => 15,
                'bentuk_pendidikan_id_str' => 'SMK',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Solontongan No. 10',
                'rt' => '01', 'rw' => '04',
                'kode_wilayah' => '026003',
                'kode_pos' => '40264',
                'nomor_telepon' => '022-7305529',
                'email' => 'info@smkn3bandung.sch.id',
                'website' => 'smkn3bandung.sch.id',
                'lintang' => '-6.936500', 'bujur' => '107.625800',
                'kecamatan' => 'Kec. Lengkong',
                'kabupaten_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],

            // --- KECAMATAN CICENDO ---
            [
                'sekolah_id' => Str::uuid(),
                'nama' => 'SMKN 12 Bandung',
                'nss' => '401026004012',
                'npsn' => '20219149',
                'kode_sekolah' => 'SMKN12BDG',
                'bentuk_pendidikan_id' => 15,
                'bentuk_pendidikan_id_str' => 'SMK',
                'status_sekolah' => 1,
                'status_sekolah_str' => 'Negeri',
                'alamat_jalan' => 'Jl. Pajajaran No. 92',
                'rt' => '02', 'rw' => '05',
                'kode_wilayah' => '026004',
                'kode_pos' => '40173',
                'nomor_telepon' => '022-6033144',
                'email' => 'smkn12bandung@gmail.com',
                'website' => 'smkn12bandung.sch.id',
                'lintang' => '-6.905600', 'bujur' => '107.585500',
                'kecamatan' => 'Kec. Cicendo',
                'kabupaten_kota' => 'Kota Bandung',
                'provinsi' => 'Jawa Barat',
                'logo' => null, 'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        DB::table('sekolahs')->insert($dataSekolah);
    }
}